# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addHotel.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HotelAddForm(object):
    def setupUi(self, HotelAddForm):
        HotelAddForm.setObjectName("HotelAddForm")
        HotelAddForm.resize(291, 180)
        self.buttonBox = QtWidgets.QDialogButtonBox(HotelAddForm)
        self.buttonBox.setGeometry(QtCore.QRect(110, 140, 168, 26))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        # self.buttonBox.setStandardButtons(QtCore.Qt.QDialogButtonBox::StandardButton::Cancel|QtCore.Qt.QDialogButtonBox::StandardButton::Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.hotelName = QtWidgets.QLineEdit(HotelAddForm)
        self.hotelName.setGeometry(QtCore.QRect(150, 40, 113, 26))
        self.hotelName.setObjectName("hotelName")
        # self.roomCount = QtWidgets.QLineEdit(HotelAddForm)
        # self.roomCount.setGeometry(QtCore.QRect(150, 80, 113, 26))
        # self.roomCount.setObjectName("roomCount")
        self.label = QtWidgets.QLabel(HotelAddForm)
        self.label.setGeometry(QtCore.QRect(5, 40, 121, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(HotelAddForm)
        self.label_2.setGeometry(QtCore.QRect(5, 80, 141, 20))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(HotelAddForm)
        QtCore.QMetaObject.connectSlotsByName(HotelAddForm)

    def retranslateUi(self, HotelAddForm):
        _translate = QtCore.QCoreApplication.translate
        HotelAddForm.setWindowTitle(_translate("HotelAddForm", "Добавление отеля"))
        self.label.setText(_translate("HotelAddForm", "Название отеля"))
        # self.label_2.setText(_translate("HotelAddForm", "Количество комнат"))
