# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UIforms/BookForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(745, 459)
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(10, 40, 161, 21))
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 20, 121, 16))
        self.label.setObjectName("label")
        self.uploadBtn = QtWidgets.QPushButton(Form)
        self.uploadBtn.setGeometry(QtCore.QRect(10, 80, 161, 31))
        self.uploadBtn.setObjectName("uploadBtn")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(10, 221, 121, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(10, 271, 256, 171))
        self.textBrowser.setObjectName("textBrowser")
        self.spinBox = QtWidgets.QSpinBox(Form)
        self.spinBox.setGeometry(QtCore.QRect(200, 220, 121, 22))
        self.spinBox.setObjectName("spinBox")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 200, 171, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(200, 200, 231, 16))
        self.label_3.setObjectName("label_3")
        self.bookBtn = QtWidgets.QPushButton(Form)
        self.bookBtn.setGeometry(QtCore.QRect(270, 400, 151, 41))
        self.bookBtn.setObjectName("bookBtn")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 250, 47, 13))
        self.label_4.setObjectName("label_4")
        self.updateBtn = QtWidgets.QPushButton(Form)
        self.updateBtn.setGeometry(QtCore.QRect(220, 80, 161, 31))
        self.updateBtn.setObjectName("updateBtn")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(430, 10, 301, 431))
        # self.tableWidget.setSizeAdjustPolicy(QtCore.Qt.QAbstractScrollArea::SizeAdjustPolicy::AdjustToContents)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.fio = QtWidgets.QLineEdit(Form)
        self.fio.setGeometry(QtCore.QRect(10, 166, 181, 20))
        self.fio.setObjectName("fio")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 140, 111, 18))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Бронирование комнаты"))
        self.label.setText(_translate("Form", "Выберите отель"))
        self.uploadBtn.setText(_translate("Form", "Загрузить данные"))
        self.label_2.setText(_translate("Form", "Введите номер комнаты"))
        self.label_3.setText(_translate("Form", "Кол-во суток для бронирования"))
        self.bookBtn.setText(_translate("Form", "Забронировать!"))
        self.label_4.setText(_translate("Form", "Чек"))
        self.updateBtn.setText(_translate("Form", "Обновить данные"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "№ Комнаты"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "ID Отеля"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Стоимость "))
        self.label_5.setText(_translate("Form", "Введите ФИО"))
