# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'employerForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdminForm(object):
    def setupUi(self, AdminForm):
        AdminForm.setObjectName("AdminForm")
        AdminForm.resize(600, 252)
        self.comboBox = QtWidgets.QComboBox(AdminForm)
        self.comboBox.setGeometry(QtCore.QRect(20, 30, 201, 26))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(AdminForm)
        self.label.setGeometry(QtCore.QRect(20, 10, 161, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(AdminForm)
        self.label_2.setGeometry(QtCore.QRect(290, 30, 171, 20))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(AdminForm)
        self.lineEdit.setGeometry(QtCore.QRect(470, 30, 113, 26))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.addHotelBtn = QtWidgets.QPushButton(AdminForm)
        self.addHotelBtn.setGeometry(QtCore.QRect(20, 80, 201, 26))
        self.addHotelBtn.setObjectName("addHotelBtn")
        self.delHotelBtn = QtWidgets.QPushButton(AdminForm)
        self.delHotelBtn.setGeometry(QtCore.QRect(20, 120, 201, 26))
        self.delHotelBtn.setObjectName("delHotelBtn")
        self.seeHotelBtn = QtWidgets.QPushButton(AdminForm)
        self.seeHotelBtn.setGeometry(QtCore.QRect(20, 160, 201, 31))
        self.seeHotelBtn.setObjectName("seeHotelBtn")
        self.updateBtn = QtWidgets.QPushButton(AdminForm)
        self.updateBtn.setGeometry(QtCore.QRect(20, 200, 201, 31))
        self.updateBtn.setObjectName("seeHotelBtn_2")

        self.retranslateUi(AdminForm)
        QtCore.QMetaObject.connectSlotsByName(AdminForm)

    def retranslateUi(self, AdminForm):
        _translate = QtCore.QCoreApplication.translate
        AdminForm.setWindowTitle(_translate("AdminForm", "АРМ Работника"))
        self.comboBox.setItemText(0, _translate("AdminForm", "Не выбрано"))
        self.label.setText(_translate("AdminForm", "Выберите отель"))
        self.label_2.setText(_translate("AdminForm", "Текущий пользователь:"))
        self.addHotelBtn.setText(_translate("AdminForm", "Добавить отель"))
        self.delHotelBtn.setText(_translate("AdminForm", "Удалить отель"))
        self.seeHotelBtn.setText(_translate("AdminForm", "Просмотр текущего отеля"))
        self.updateBtn.setText(_translate("AdminForm", "Обновить список"))
