# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(459, 362)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setStyleSheet("QWidget { background-color: cyan;}")
        self.exitBtn = QtWidgets.QPushButton(self.centralwidget)
        self.exitBtn.setGeometry(QtCore.QRect(340, 290, 88, 26))
        self.exitBtn.setObjectName("exitBtn")
        
        self.loginField = QtWidgets.QLineEdit(self.centralwidget)
        self.loginField.setGeometry(QtCore.QRect(90, 50, 141, 26))
        self.loginField.setObjectName("loginFiel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(24, 50, 66, 18))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(24, 100, 66, 18))
        self.label_2.setObjectName("label_2")
        # self.clientRB = QtWidgets.QRadioButton(self.centralwidget)
        # self.clientRB.setGeometry(QtCore.QRect(340, 50, 111, 24))
        # self.clientRB.setObjectName("clientRB")
        
        # self.workerRB = QtWidgets.QRadioButton(self.centralwidget)
        # self.workerRB.setGeometry(QtCore.QRect(340, 90, 111, 24))
        # self.workerRB.setObjectName("workerRB")
        
        self.loginBtn = QtWidgets.QPushButton(self.centralwidget)
        self.loginBtn.setGeometry(QtCore.QRect(20, 170, 101, 26))
        self.loginBtn.setObjectName("loginBtn")
        self.loginBtn.setEnabled(False)
        self.regBtn = QtWidgets.QPushButton(self.centralwidget)
        self.regBtn.setGeometry(QtCore.QRect(130, 170, 101, 26))
        self.regBtn.setObjectName("regBtn")
        
        self.passwdField = QtWidgets.QLineEdit(self.centralwidget)
        self.passwdField.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwdField.setGeometry(QtCore.QRect(90, 100, 141, 26))
        self.passwdField.setObjectName("passwdField")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 459, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hotel System"))
        self.exitBtn.setText(_translate("MainWindow", "Выход"))
        self.label.setText(_translate("MainWindow", "Логин"))
        self.label_2.setText(_translate("MainWindow", "Пароль"))
        self.loginBtn.setText(_translate("MainWindow", "Войти"))
        self.regBtn.setText(_translate("MainWindow", "Регистрация"))
