# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UIforms\requestsForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RequestsForm(object):
    def setupUi(self, RequestsForm):
        RequestsForm.setObjectName("RequestsForm")
        RequestsForm.resize(530, 443)
        self.tableWidget = QtWidgets.QTableWidget(RequestsForm)
        self.tableWidget.setGeometry(QtCore.QRect(10, 20, 501, 361))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.label = QtWidgets.QLabel(RequestsForm)
        self.label.setGeometry(QtCore.QRect(10, 400, 231, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(RequestsForm)
        self.lineEdit.setGeometry(QtCore.QRect(150, 400, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(RequestsForm)
        self.pushButton.setGeometry(QtCore.QRect(394, 400, 111, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(RequestsForm)
        QtCore.QMetaObject.connectSlotsByName(RequestsForm)

    def retranslateUi(self, RequestsForm):
        _translate = QtCore.QCoreApplication.translate
        RequestsForm.setWindowTitle(_translate("RequestsForm", "Просмотр заявок"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("RequestsForm", "№"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("RequestsForm", "Комната"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("RequestsForm", "Отель"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("RequestsForm", "Услуга"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("RequestsForm", "Дата"))
        self.label.setText(_translate("RequestsForm", "Ответить на заявку номер:"))
        self.pushButton.setText(_translate("RequestsForm", "Ответить"))
